python: can't open file '/var/tmp/pbs.6803251.pbs/run_cpp_file.py': [Errno 2] No such file or directory
/rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_linkcounting_mass_1.0_N_multiplier_400_N_reps_10.sh: line 27: 3777417 Segmentation fault      ./${runfilename::-4}".exe" $mass $N_multiplier $N_reps
